### ISSUE TITLE
issue 기능 요청

### ISSUE THREAD

**Issue by ww8007** [JerryK026/random-interview-defense#12]
1. RID에 대해서 소문자 rid 명령어도 등록해 주세요

2. 가장 최근에 나왔던 질문에 대해서 rid r 같은 명령어로 바로 확인할 수 있게 부탁 드려요 😃

**Comment by JerryK026** [comment]
기능 요청 감사합니다! 생각해보니 정말 편리할 것 같은 기능이네요 다음 기능 추가 때 추가해보겠습니다!
rid --help도 만들면 좋을 것 같네요 :)

**Comment by JerryK026** [comment]
이번 배포에서 해결했습니다! 의견 주셔서 감사합니다 :D
