### ISSUE TITLE
powerlevel 사용시 초기화 중 콘솔 출력 감지 경고 제거

### ISSUE THREAD

**Issue by wooogy-dev** [JerryK026/random-interview-defense#7]
<img width="771" alt="image" src="https://user-images.githubusercontent.com/22572874/212272252-7da27d6d-231a-40cb-b4c4-90706b412417.png">

mac: `vi ~/.p10k.zsh` or `vi ~/.p9k.zsh`

해당 라인 off로 변경
`typeset -g POWERLEVEL9K_INSTANT_PROMPT=off`

해당 부분 README에 추가되어도 좋을 것 같습니다.

**Comment by JerryK026** [comment]
안녕하세요! 찾아보니 Powerlevel10k를 사용하는 경우 instant prompt 옵션을 verbose로 줬을 때 발생하는 것 같네요. 문의 주셔서 감사드리고 도움이 되었습니다! 다음 README 업데이트 때 적용하도록 하겠습니다!

**Comment by JerryK026** [comment]
README.md에 적용되었습니다! 해당 이슈는 닫도록 하겠습니다 :D 감사합니다!
